{
 "title": "OneOS",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": {
     "query": "from(bucket: \"oneos_snmp\")\r\n  |> range(start: -1d)\r\n  |> keep(columns: [\"hostname\"])\r\n  |> distinct(column: \"hostname\")\r\n  |> sort()\r\n  |> yield(name: \"distinct\")"
    }
   }
  ]
 },
 "panels": [
  { "title": "Alarmes", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "Availability",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"oneos_snmp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n  |> aggregateWindow(every: 1m, fn: count, createEmpty: true)\r\n  |> map(fn: (r) => ({\r\n        r with _value: if r._value > 0 then 1 else 0\r\n      }))"
    }
   ]
  },
  {
   "title": "SLA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "query": "from(bucket: \"oneos_snmp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rtt\" or r[\"_field\"] == \"packetLoss\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _field: if r._field == \"rtt\" then \"Average Round Trip Time in ms\" else \"Lost packets out of 10 samples\"\r\n    }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "query": "from(bucket: \"oneos_snmp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ifHCInOctets\" or r[\"_field\"] == \"ifHCOutOctets\")\r\n  |> filter(fn: (r) => r[\"ifName\"] =~ /Gigabit/)\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _value: (r._value * 8.0) / (1024.0 * 1024.0),\r\n      _field: if r._field == \"ifHCInOctets\" then r[\"ifName\"]+\" IN\" else r[\"ifName\"]+\" OUT\"\r\n  }))\r\n  |> keep(columns: [\"_time\",\"_value\",\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"oneos_snmp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"oacSysCpuUsedValue\")\r\n  |> map(fn: (r) => ({\r\n        r with \r\n        cpu_label: \"Used CPU (core ${string(v: r.oacSysCpuUsedIndex)})\"\r\n      }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"oneos_snmp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"memFree\" or r[\"_field\"] == \"memTotal\")\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _value: r._value,\r\n      _field: if r._field == \"memFree\" then \"Free\" else \"Total\"\r\n  }))  \r\n  |> keep(columns: [\"_time\",\"_value\",\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}